name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-13, macos-15]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install SBCL on Linux
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: sudo apt-get install sbcl
    - name: Install SBCL on macOS
      if: ${{ startsWith(matrix.os, 'mac') }}
      run: brew install sbcl

    - name: Download Quicklisp
      run: curl -O https://beta.quicklisp.org/quicklisp.lisp
    - name: Install Quicklisp
      run: sbcl --non-interactive --load quicklisp.lisp --eval '(quicklisp-quickstart:install)' --eval '(ql-util:without-prompting (ql:add-to-init-file))'

    - name: Build and test
      run: make

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: m3f-${{ runner.os }}-${{ runner.arch }}
        path: m3f
