name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-linux:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install SBCL
      run: sudo apt-get install sbcl

    - name: Install Quicklisp
      run: |
        curl -O https://beta.quicklisp.org/quicklisp.lisp
        sbcl --non-interactive --load quicklisp.lisp --eval '(quicklisp-quickstart:install)' --eval '(ql-util:without-prompting (ql:add-to-init-file))'

    - name: Build and test
      run: make

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: m3f-${{ runner.os }}-${{ runner.arch }}
        path: m3f

  build-mac:
    runs-on: [macos-13, macos-15]
    steps:
    - uses: actions/checkout@v4
    - name: Install SBCL
      run: sudo brew install sbcl
    - name: Install Quicklisp
      run: |
        curl -O https://beta.quicklisp.org/quicklisp.lisp
        sbcl --non-interactive --load quicklisp.lisp --eval '(quicklisp-quickstart:install)' --eval '(ql-util:without-prompting (ql:add-to-init-file))'

    - name: Build and test
      run: make

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: m3f-${{ runner.os }}-${{ runner.arch }}
        path: m3f
